name: LFE
channels:
  - defaults
  - pytorch  
dependencies:
  - python=3.8
  - numpy
  - pandas
  - matplotlib
  - torch
  - torchvision
  - captum  
  - scipy
  - tqdm
  - pillow
  - seaborn
  - pathlib  
  - wget
  - pip
  - pip:
    - medmnist 
