name: LFE
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - numpy
  - pandas
  - matplotlib
  - torchvision
  - captum  
  - pytorch
  - tabulate
  - scipy
  - tqdm
  - pillow
  - seaborn
  - pathlib  
  - pip
  - pip:
    - medmnist  
    - torch
    - wget
    - hydra
